CREATE DATABASE SHOP

CREATE TABLE PRODUCT(
    P_CODE INT AUTO_INCREMENT PRIMARY KEY,
    P_NAME VARCHAR(20) NOT NULL,
    P_PRICE VARCHAR(10) NOT NULL,
    P_IMG  VARCHAR(50)  NOT NULL
)
;


CREATE TABLE STAFF(
    CODE INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    PASSWORD  VARCHAR(50)
);



CREATE TABLE  DATA_SALES(
    ORDERCODE INT  AUTO_INCREMENT PRIMARY KEY,
    DATE TIMESTAMP  
    MEMBER_CODE INT NOT NULL,
    NAME VARCHAR(20),
    EMAIL VARCHAR(50),
    FIRST_POST  VARCHAR(3),
    SECOND_POST VARCHAR(4),
    ADDRESS  VARCHAR(50),
    TEL VARCHAR(13)

);

CREATE TABLE DATA_SALES(
  CODE INT AUTO_INCREMENT PRIMARY KEY,
  CODE_SALES INT ,
  CODE_PRODUCT INT ,
  PRICE  INT ,
  QUANTITY  INT 
)
;